---
- name: restart grafana
  systemd:
    name: "{{ grafana_service_name }}"
    state: restarted
    daemon_reload: yes

- name: reload grafana
  systemd:
    name: "{{ grafana_service_name }}"
    state: reloaded
    daemon_reload: yes
# handlers file for grafana
